---
- hosts: otp_ssh_clients
  remote_user: ubuntu
  become: true
  tasks:
    - name: update files on the ssh otp clients
      script: /Users/wendysegura/Desktop/SecretLock/terraform-ssh-clients/ansible/scripts/otp-userdata.sh
    - name: copy over ca-cert file needed to talk to vault
      copy:
        src: /Users/wendysegura/.keys/ca.cert.pem
        dest: /etc/vault-ssh-helper.d/ca_public_key.pem
